version: '3.8'

services:
  db:
    container_name: postgres_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
      - "5432:5432"
    volumes: 
      - pgdata:/var/lib/postgresql/data
    networks:
        - gorgesMusic_network
  gorgesmusicbackend:
    container_name: gorgesMusic_backend
    image: ${DOCKER_REGISTRY-}gorgesmusicbackend
    build:
      context: .
      dockerfile: GorgesMusicBackend/Dockerfile
    networks:
      - gorgesMusic_network
volumes:
    pgdata:
networks:
    gorgesMusic_network:
        driver: bridge